language: node_js
node_js: node
services:
  - postgresql
before_script:
  - psql -c 'create database tuba;' -U postgres
  - npm run build
cache:
  directories:
    - node_modules 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
